version: "0.0.0"

services:
  frontend:
    build: ./app/frontend
    container_name: frontend
    ports:
      - "80:80"
    restart: always
    environment:
      - PORT=80
      - VITE_NODE_BACKEND_URI_CONTAINER=http://node_backend:3000

  node_backend:
    build: ./app/node-backend
    container_name: node_backend
    ports:
      - "3000:3000"
    restart: always
    environment:
      - BASE_AWS_URL=http://ec2-54-70-150-226.us-west-2.compute.amazonaws.com
      - OPENEOCUBES_URI=http://openeocubes:8000

  openeocubes:
    build: ./app/r_backend/openeocubes
    container_name: openeocubes
    ports:
      - "8000:8000"
    restart: always
    environment:
      - TZ=Etc/UTC
      - DEBIAN_FRONTEND=noninteractive
