name: Deploy Frontend

on:
  workflow_run:
    workflows: ["Lint Frontend"]
    types:
    - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "webml-openeo"
          heroku_email: "l.wittrock@ymail.com"
          appdir: "./app/frontend"
          usedocker: true
